server.port: 8080
scriptPath: "/home/vsevolod/deploy/test.sh"
spring:
  datasource:
    host: 91.186.197.234
    url: jdbc:postgresql://${spring.datasource.host}:5432/tester
    username: mynewuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
